{
 "title": "sFlow-RT Health",
 "description": "sFlow-RT analytics engine health metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "sFlow Agents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sflow_analyzer_agent_count[$__interval])",
     "legendFormat": "Agents"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sflow_analyzer_cpu_load_process[$__interval])",
     "legendFormat": "Application"
    },
    {
     "expr": "avg_over_time(sflow_analyzer_cpu_load_system[$__interval])",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "sFlow Packet Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sflow_analyzer_received_datagrams",
     "legendFormat": "Packets Received"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sflow_analyzer_heap_used_bytes[$__interval])",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(sflow_analyzer_heap_max_bytes[$__interval])",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "sFlow Byte Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "sflow_analyzer_received_bytes", "legendFormat": "Bytes Received" }
   ]
  },
  {
   "title": "HTTP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sflow_analyzer_http_connections_current[$__interval])",
     "legendFormat": "Connections"
    }
   ]
  }
 ]
}